definitions:
  models.AccessToken:
    properties:
      access:
        type: string
    type: object
  models.Error:
    properties:
      message:
        type: string
    type: object
  models.ListResume:
    properties:
      resumes:
        items:
          $ref: '#/definitions/models.Resume'
        type: array
    type: object
  models.ListUsers:
    properties:
      count:
        type: integer
      users:
        items:
          $ref: '#/definitions/models.UserBody'
        type: array
    type: object
  models.ReqResume:
    properties:
      birth_date:
        example: "2020-01-01"
        type: string
      category_id:
        type: string
      description:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      salary:
        type: string
    type: object
  models.Resume:
    properties:
      birth_date:
        example: "2020-01-01"
        type: string
      category_id:
        type: string
      description:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      salary:
        type: string
      user_id:
        type: string
      work_type:
        type: string
    type: object
  models.StandardErrorModel:
    properties:
      error:
        $ref: '#/definitions/models.Error'
    type: object
  models.UpdateResume:
    properties:
      birth_date:
        example: "2020-01-01"
        type: string
      category_id:
        type: string
      description:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      salary:
        type: string
    type: object
  models.UpdateUserReq:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      user_id:
        type: string
      user_name:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      image_url:
        type: string
      last_name:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
  models.UserBody:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      image_url:
        type: string
      last_name:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
host: 18.158.24.26:9050
info:
  contact: {}
  title: Generate resume
  version: "1.7"
paths:
  /v1/auth/login/:
    post:
      consumes:
      - application/json
      description: LogIn - Api for registering users
      parameters:
      - description: Password
        in: query
        name: password
        required: true
        type: string
      - description: Email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccessToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: LogIn
      tags:
      - Register
  /v1/auth/register/:
    post:
      consumes:
      - application/json
      description: Register - Api for registering users
      parameters:
      - description: createRegisterModel
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: Register
      tags:
      - Register
  /v1/auth/verification/:
    post:
      consumes:
      - application/json
      description: Verification - Api for registering users
      parameters:
      - description: Code
        in: query
        name: code
        required: true
        type: integer
      - description: Email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccessToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: Verification
      tags:
      - Register
  /v1/resume/all/:
    get:
      consumes:
      - application/json
      description: GetAllResume - Api for get resume
      parameters:
      - description: field
        in: query
        name: field
        type: integer
      - description: value
        in: query
        name: value
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ListResume'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: GetAllResume
      tags:
      - Resume
  /v1/resume/create/:
    post:
      consumes:
      - application/json
      description: CreateResume - Api for create resume
      parameters:
      - description: createResumeModel
        in: body
        name: CreateResume
        schema:
          $ref: '#/definitions/models.ReqResume'
      - description: work_type
        enum:
        - offline
        - online
        - does not matter
        in: query
        name: work_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Resume'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      security:
      - ApiKeyAuth: []
      summary: CreateResume
      tags:
      - Resume
  /v1/resume/delete/:
    delete:
      consumes:
      - application/json
      description: DeleteResume - Api for get users
      parameters:
      - in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      security:
      - ApiKeyAuth: []
      summary: DeleteResume
      tags:
      - Resume
  /v1/resume/get/:
    get:
      consumes:
      - application/json
      description: GetResume - Api for get users
      parameters:
      - description: field
        in: query
        name: field
        type: string
      - description: value
        in: query
        name: value
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Resume'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: GetResume
      tags:
      - Resume
  /v1/resume/update/:
    put:
      consumes:
      - application/json
      description: UpdateResume - Api for get users
      parameters:
      - description: updateUserModel
        in: body
        name: UpdateResume
        required: true
        schema:
          $ref: '#/definitions/models.UpdateResume'
      - description: work_type
        enum:
        - offline
        - online
        - does not matter
        in: query
        name: work_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      security:
      - ApiKeyAuth: []
      summary: UpdateResume
      tags:
      - Resume
  /v1/user/all/:
    get:
      consumes:
      - application/json
      description: GetAllUsers - Api for get users
      parameters:
      - description: field
        in: query
        name: field
        type: integer
      - description: value
        in: query
        name: value
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ListUsers'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: GetAllUsers
      tags:
      - User
  /v1/user/delete/:
    delete:
      consumes:
      - application/json
      description: DeleteUser - Api for get users
      parameters:
      - in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      security:
      - ApiKeyAuth: []
      summary: DeleteUser
      tags:
      - User
  /v1/user/get/:
    get:
      consumes:
      - application/json
      description: GetUser - Api for get users
      parameters:
      - description: field
        in: query
        name: field
        type: string
      - description: value
        in: query
        name: value
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: GetUser
      tags:
      - User
  /v1/user/update/:
    put:
      consumes:
      - application/json
      description: UpdateUser - Api for get users
      parameters:
      - description: updateUserModel
        in: body
        name: UpdateUser
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      security:
      - ApiKeyAuth: []
      summary: UpdateUser
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
