services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
      POSTGRES_DB: generator_resume
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5332"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redisdb:
    container_name: redisdb
    image:  redis
    ports:
      - "6378:6378"
    networks:
      - db

  resume-generator:
    container_name: resume-generator
    build: ./
    depends_on:
      -  "redisdb"
      -  "db"
    ports:
      - "9050:9050"
    networks:
      - db

  migrate:
    image: migrate/migrate
    networks:
      - db
    volumes:
      - ./migrations:/migrations
    command: -path /migrations -database postgres://postgres:123@db:5432/generator_resume?sslmode=disable -verbose up
    links:
      - db
    depends_on:
      - "db"



networks:
  db:
    driver: bridge

volumes:
  db:


